swagger: "2.0"
info:
  title: Calculator API
  description: API for a simple calculator
  version: 1.0.0

host: calculator.apigateway.involuted-alpha-415222.cloud.goog
basePath: /
schemes:
  - https
  - http

paths:
  /add:
    post:
      operationId: add
      summary: Add two numbers.
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Numbers to add
          required: true
          schema:
            type: object
            properties:
              X:
                type: number
              Y:
                type: number
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-involuted-alpha-415222.cloudfunctions.net/add

  /sub:
    post:
      operationId: sub
      summary: Subtract two numbers.
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Numbers to subtract
          required: true
          schema:
            type: object
            properties:
              X:
                type: number
              Y:
                type: number
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-involuted-alpha-415222.cloudfunctions.net/sub

  /mul:
    post:
      operationId: mul
      summary: Multiply two numbers.
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Numbers to multiply
          required: true
          schema:
            type: object
            properties:
              X:
                type: number
              Y:
                type: number
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-involuted-alpha-415222.cloudfunctions.net/mul

  /div:
    post:
      operationId: div
      summary: Divide two numbers.
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Numbers to divide
          required: true
          schema:
            type: object
            properties:
              X:
                type: number
              Y:
                type: number
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-involuted-alpha-415222.cloudfunctions.net/div
